name: Release dev builds

on:
  push:
    branches: [main, testing, dev]
  workflow_run:
    workflows: [Java CI with Gradle]
    types: [completed]
    branches: [main, testing, dev]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            codecov: true
          - os: windows-latest
            codecov: false
          - os: macos-latest
            codecov: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: PiazzaPanic/desktop:dist
      - name: Test
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: PiazzaPanic/tests:test
      - name: Report Test
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: "${{ matrix.os }} Test Report"
          path: PiazzaPanic/tests/build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        if: ${{ matrix.codecov && success()}}
        with:
          dotnet-version: 6.x
          dotnet-quality: 'ga'
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.17
        if: ${{ matrix.codecov && success()}}
        with:
          reports: PiazzaPanic/tests/build/jacoco.xml
          targetdir: out
          reporttypes: MarkdownSummaryGithub
      - name: Publish Coverage Report
        uses: PavanMudigonda/markdown-reporter@v0.1
        if: ${{ matrix.codecov && success()}}
        with:
          markdown_path: out/SummaryGithub.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_name: Coverage Report
          report_title: Code Coverage Report


      - name: Rename jar file
        if: matrix.os == 'ubuntu-latest'
        run: |
          pwd
          ls -la
          cd PiazzaPanic/desktop/build/libs
          VER=`git rev-parse --short HEAD`
          mv desktop-1.0.jar team17-piazzaPanic.jar
      - name: Automatically release
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-dev
          name: "Development Build"
          prerelease: true
          files: |
            PiazzaPanic/desktop/build/libs/*.jar
