name: Release dev builds

on:
  push:
    branches:
      - main
      - testing
      - dev
  workflow_run:
    workflows:
      - "Java CI with Gradle"
    types:
      - completed
    branches:
      - main
      - testing
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Debug
        run: echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Gradle
        working-directory: ./PiazzaPanic
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1
          arguments: desktop:dist

      - name: Rename jar file
        working-directory: ./PiazzaPanic/desktop/build/libs
        run: |
          VER=$(git rev-parse --short HEAD)
          mv desktop-1.0.jar team17-piazzaPanic.jar

      - name: Automatically release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-dev"
          prerelease: true
          title: "Development Build"
          files: |
            PiazzaPanic/desktop/build/libs/team17-piazzaPanic.jar
