name: Release dev builds

on:
  push:
    branches: [main, testing, dev]
  workflow_run:
    workflows: [Java CI with Gradle]
    types: [completed]
    branches: [main, testing, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        working-directory: ./PiazzaPanic
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7.1
          arguments: desktop:dist
      - name: Rename jar file
        run: |
          cd PiazzaPanic/desktop/build/libs
          VER=`git rev-parse --short HEAD`
          mv desktop-1.0.jar team17-piazzaPanic.jar
      - name: Automatically release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-dev
          name: "Development Build"
          prerelease: true
          files: |
            PiazzaPanic/desktop/build/libs/*.jar

